apiVersion: v1
kind: Pod
metadata:
  name: secondapp
spec:
  serviceAccountName: secret-access-sa
  securityContext:
    runAsUser: 1000
  containers:
  - image: busybox
    name: secondapp
    command:
      - sleep
      - "3600"
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
    volumeMounts:
    - mountPath: /mysqlPassword
      name: mysql
    name: busy
  volumes:
  - name: mysql
    secret:
      secretName: lfsecret
